version: '3'

services:
  texteditor:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - XDG_RUNTIME_DIR
      - WAYLAND_DISPLAY
    volumes:
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}
    command: ["/go/bin/texteditor"]
    entrypoint:
      - /go/bin/texteditor

